name: JavaScript linting

on:
  push:
    branches:
      - main
      - "[0-9]*"
    paths:
      - "**.cjs"
      - "**.mjs"
      - "**.json"
      - package*.json
      - ".*eslint*"
      - ".*prettier*"
      - .github/workflows/lint.yml
  pull_request:
    branches:
      - main
      - "[0-9]*"
    paths:
      - "**.cjs"
      - "**.mjs"
      - "**.json"
      - package*.json
      - ".*eslint*"
      - ".*prettier*"
      - .github/workflows/lint.yml

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci --force
      - name: eslint
        run: npm run test:lint
      - name: Prettier
        run: npm run test:format
