name: JavaScript linting

on:
  push:
    branches:
      - main
      - "[0-9]*"
    paths:
      - "**.jsx?"
      - "**.cjs"
      - "**.mjs"
      - "**.json"
      - package*.json
      - ".*eslint*"
      - ".*prettier*"
      - .github/workflows/lint.yml
  pull_request:
    branches:
      - main
      - "[0-9]*"
    paths:
      - "**.jsx?"
      - "**.cjs"
      - "**.mjs"
      - "**.json"
      - package*.json
      - ".*eslint*"
      - ".*prettier*"
      - .github/workflows/lint.yml

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: eslint
        run: npm run test:lint
      - name: Prettier
        run: npm run test:format
