name: Unit Tests

on:
  push:
    branches:
      - main
      - "[0-9]*"
    paths:
      - addon/**
      - scripts/**
      - babel.config.cjs
      - package*.json
      - webpack.config.cjs
      - .github/workflows/unit.yml
  pull_request:
    branches:
      - main
      - "[0-9]*"
    paths:
      - addon/**
      - scripts/**
      - babel.config.cjs
      - package*.json
      - webpack.config.cjs
      - .github/workflows/unit.yml

jobs:
  eslint:
    name: unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci --force
      - name: Run node tests
        run: npm run test:node
