name: Unit Tests

on:
  push:
    branches:
      - main
      - "[0-9]*"
    paths:
      - addon/**
      - scripts/**
      - babel.config.cjs
      - package*.json
      - webpack.config.cjs
      - .github/workflows/unit.yml
  pull_request:
    branches:
      - main
      - "[0-9]*"
    paths:
      - addon/**
      - scripts/**
      - babel.config.cjs
      - package*.json
      - webpack.config.cjs
      - .github/workflows/unit.yml

jobs:
  eslint:
    name: unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Run jest tests
        run: npm run test:jest
