name: Unit Tests

on:
  push:
    branches:
      - main
      - "[0-9]*"
    paths:
      - addon/**
      - scripts/**
      - babel.config.cjs
      - package*.json
      - webpack.config.cjs
      - .github/workflows/unit.yml
  pull_request:
    branches:
      - main
      - "[0-9]*"
    paths:
      - addon/**
      - scripts/**
      - babel.config.cjs
      - package*.json
      - webpack.config.cjs
      - .github/workflows/unit.yml

jobs:
  eslint:
    name: unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci --force
      - name: Run jest tests
        run: npm run test:jest
